version: '0.7.0-{build}'

os: Visual Studio 2015
platform: x86
clone_folder: C:\USBqemu-wheel
clone_depth: 3
test: off
skip_non_tags: true

configuration:
 - Release
 - RelWithDebInfo

before_build:
 - ps: $env:Date="$(git show -s --date=short --format='%ad')"
 - cmd: mkdir build
 - cmd: cd build
 - cmake -G "Visual Studio 14" ..

build_script:
 - cmake --build . --config %configuration% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

install:
 - set COMMIT_SHA=%APPVEYOR_REPO_COMMIT:~0,8%

artifacts:
 - path: build\$(configuration)
   name: 'USBqemu-wheel-$(APPVEYOR_BUILD_VERSION)-$(Date)-$(COMMIT_SHA)-$(configuration)'
   type: zip
